"""
build-scripts/generate_api_types.py — OpenAPI → TypeScript codegen.

Layer C5 of the architectural plan. Builds a bare FastAPI app with every
backend router registered (via ``server.register_routers``), dumps its
``app.openapi()`` schema to a temp JSON file, then runs
``openapi-typescript`` against it to emit
``desktop-ui/api/generated.d.ts``.

Why this is better than the previous walk-the-BaseModels approach:
  * The route table is the source of truth — adding a new ``BaseModel``
    that the renderer should know about now means registering it as a
    request or response model on a real endpoint, which is the thing
    that makes it actually callable. The old codegen would silently
    include any class in the allowlisted modules whether or not it was
    exposed.
  * openapi-typescript emits ``paths`` types alongside ``components.schemas``,
    so future call sites can pin both request bodies and response shapes
    against the live wire contract.
  * One toolchain (npx openapi-typescript) replaces the previous two
    (pydantic2ts + json-schema-to-typescript).

CI fails when re-running this script would change the output (drift gate
in .github/workflows/tests.yml). Operators regenerate locally and commit
the diff alongside the underlying schema change:

    python build-scripts/generate_api_types.py
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import subprocess
import sys
import tempfile
import textwrap
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BACKEND_DIR = REPO_ROOT / "backend"
DEFAULT_OUTPUT = REPO_ROOT / "desktop-ui" / "api" / "generated.d.ts"


def _build_openapi_only_app():
    """Return a FastAPI instance with every router registered but no services
    started. Sufficient for ``app.openapi()`` — route signatures and Pydantic
    models are introspected at registration time, not at request time."""
    # Make ``import server``, ``import routes.*`` resolve from backend/ whether
    # we're invoked from the repo root or from build-scripts/.
    if str(BACKEND_DIR) not in sys.path:
        sys.path.insert(0, str(BACKEND_DIR))

    from fastapi import FastAPI

    from server import OPENAPI_TITLE, OPENAPI_VERSION, register_routers

    app = FastAPI(title=OPENAPI_TITLE, version=OPENAPI_VERSION)
    register_routers(app)
    return app


_HEADER = textwrap.dedent("""\
    /**
     * AUTO-GENERATED by build-scripts/generate_api_types.py — do not edit.
     *
     * OpenAPI schema dumped from backend/server.py:build_app() and translated
     * into TypeScript via openapi-typescript. The CI gate in
     * .github/workflows/tests.yml re-runs the codegen on every PR and fails
     * if this file would change — keep it in sync by regenerating locally:
     *
     *     python build-scripts/generate_api_types.py
     *
     * Then commit the diff alongside the underlying schema change.
     */
""")


def _prepend_header(output: Path) -> None:
    body = output.read_text(encoding="utf-8")
    output.write_text(_HEADER + "\n" + body, encoding="utf-8")


def _resolve_npx() -> str:
    """Pick the right npx invocation for the current platform.

    On Windows the executable is ``npx.cmd``; ``subprocess`` without
    ``shell=True`` won't auto-resolve the ``.cmd`` extension. On POSIX
    it's just ``npx``. Both CI (Ubuntu) and local Windows dev hit this.
    """
    return "npx.cmd" if platform.system() == "Windows" else "npx"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output", type=Path, default=DEFAULT_OUTPUT,
        help="Path to write the generated .d.ts (default: %(default)s)",
    )
    parser.add_argument(
        "--openapi-typescript-cmd", default=None,
        help=(
            "Override the openapi-typescript binary. Default uses npx so the "
            "locally-installed npm package is picked up after `npm ci`."
        ),
    )
    args = parser.parse_args(argv)

    app = _build_openapi_only_app()
    schema = app.openapi()

    # Sort keys so any future diff is debuggable; openapi-typescript walks the
    # spec by key not by iteration order, so this only affects readability of
    # the intermediate file, not the emitted TS.
    schema_text = json.dumps(schema, sort_keys=True, indent=2)

    args.output.parent.mkdir(parents=True, exist_ok=True)

    # tempfile.NamedTemporaryFile + delete=False because openapi-typescript
    # needs the file path to still exist when it opens it on Windows (where
    # the original handle holds an exclusive lock).
    tmp = tempfile.NamedTemporaryFile(
        mode="w", suffix=".openapi.json", delete=False, encoding="utf-8",
    )
    try:
        tmp.write(schema_text)
        tmp.flush()
        tmp.close()

        if args.openapi_typescript_cmd:
            cmd = args.openapi_typescript_cmd.split() + [tmp.name, "--output", str(args.output)]
        else:
            cmd = [_resolve_npx(), "--no-install", "openapi-typescript", tmp.name, "--output", str(args.output)]

        subprocess.run(cmd, check=True)
    finally:
        try:
            os.unlink(tmp.name)
        except OSError:
            pass

    _prepend_header(args.output)
    n_paths = len(schema.get("paths", {}))
    n_schemas = len(schema.get("components", {}).get("schemas", {}))
    print(
        f"Wrote {n_paths} path entries and {n_schemas} component schemas to {args.output}",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
